FROM mcr.microsoft.com/devcontainers/javascript-node:1-20-bullseye

# Enable reliable file watching in containerized environments (especially on Windows/macOS hosts)
ENV WATCHPACK_POLLING=true
ENV CHOKIDAR_USEPOLLING=true
